# Generated by Django 5.2.6 on 2025-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_servicepoint_bank_name_servicepoint_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepoint',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps link for the service point location'),
        ),
    ]
