# Generated by Django 5.2.6 on 2025-11-20 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_servicepoint_map_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration', models.DurationField(help_text='Estimated time to complete this service')),
                ('requires_documents', models.BooleanField(default=False)),
                ('priority_level', models.IntegerField(default=1, help_text='1=Normal, 2=Priority, 3=VIP')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['priority_level', 'position']},
        ),
        migrations.AddField(
            model_name='queueentry',
            name='priority_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='display_screen_url',
            field=models.URLField(blank=True, help_text='URL for public display screen'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='max_queue_length',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='organization_type',
            field=models.CharField(choices=[('government', 'Government Office'), ('bank', 'Bank'), ('hospital', 'Hospital')], default='government', max_length=50),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='supports_appointments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='supports_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='queues.servicepoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(blank=True, help_text='QR code identifier', max_length=100)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='queues.servicepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='queues.servicetype')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'unique_together': {('service_point', 'appointment_date', 'appointment_time')},
            },
        ),
        migrations.AddField(
            model_name='queueentry',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.appointment'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('view', 'View Record'), ('print', 'Print Document'), ('export', 'Export Data')], max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriorityQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority_level', models.IntegerField(choices=[(1, 'Normal'), (2, 'Priority'), (3, 'Urgent'), (4, 'Emergency')], default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_capacity', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_queues', to='queues.servicepoint')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comments', models.TextField(blank=True)),
                ('wait_time_satisfaction', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('staff_service_rating', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='queues.servicepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_correction', 'Requires Correction')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checks', to='queues.servicepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checks', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checks', to='queues.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='queueentry',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.servicetype'),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='service_points', to='queues.servicetype'),
        ),
    ]
