# Generated by Django 5.2.6 on 2025-11-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_government_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('served', 'Served'), ('abandoned', 'Abandoned'), ('paused', 'Paused')], default='waiting', max_length=10),
        ),
    ]
