# Generated by Django 5.2.6 on 2025-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_queueentry_staff_notes_servicepoint_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicepoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
    ]
