# Generated by Django 5.2.6 on 2025-11-19 10:02

from django.db import migrations, models


def remove_duplicate_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Find duplicate emails
    duplicates = User.objects.values('email').annotate(count=models.Count('id')).filter(count__gt=1, email__isnull=False)
    for dup in duplicates:
        email = dup['email']
        # Keep the first user, delete the rest
        users = User.objects.filter(email=email).order_by('id')
        users.exclude(id=users.first().id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_organization_type'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_emails),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
